= RPG Tools XYZ
:toc:

== About RPG Tools

Role playing game tools and applications from Huybrechts XYZ.

*Adventure Builder* +
The adventure builder will uses a plaintext, Markdown, or Asciidoc files together with configuration files to build adventure modules. Currently supported systems:

* Story. The system will create a directory with the required files as a bundle for you to use.
* Foundry. The system will create a Foundry VTT compendium.

*Campaign Tracker v3.0* +
> https://docs.google.com/spreadsheets/d/1ovY8G8na6QeCAW9mCbqPUAoZBB73B6MwnLqcRlx2Ekg/edit?usp=share_link

*Campaign Tracker v2.2* +
> https://docs.google.com/spreadsheets/d/1hcY4uFiO1AIiaXidalKlodo1Nm-MFGM5hCZzPGHShnw/edit?usp=sharing

*Proficiency Builder* +
> https://docs.google.com/spreadsheets/d/1T1EkyOOBqG-Mjmlic2bDapcTE47YEVj18uYSGN1aSXk/edit?usp=sharing

== Adventure Builder

=== Way of Thinking

Building a new RPG world or using an existing one is a daunting task. There is a lot of recurring information that you only want to write once but include in many other files. This project contains 2 sets of data to build an adventure.

. MODULE data is specific to an adventure.
. COMPENDIUM data is reused by multiple adventures.

Specific module information has priority over the compendium information. Your adventure's specific assets have priority over the compendium assets. The Goblin in your adventure might be different from the compendium's.

=== Way of Working

Create a new project by using the commandline. This will create a folder structure for you to complete based on default settings.

[filetree]
> project +
|-- mods +
|   |-- adventureName +
|   |   |-- assets +
|   |   |   |-- subfolders and files +
|   |   |-- module.yaml                     -> main module configuration +
|   |   |-- readme                          -> either plain text, markdown, or asciidoc

=== Way of Writing

==== Directory structure

The directory structure of a project.

[%header]
|===
| Directory      | Description
| .vscode        | Settings for visual studio code
| assets         | Global binary files like images, audio, etc.
| config         | Configuration files for the project
| dist           | aka Bin. The build script generated content (e.g., modules for foundry or other future systems?)
| mods           | The module configuration for creating modules in dist
| repo           | The configuration files that build docs and modules
| story          | The story elements for each module
|===

== Proficiency Builder

=== Way of Thinking
How OP is a build?

=== Way of Working
Add proficiencies and build what you like.

=== Way of Writing
Follow the google sheet link: +
> https://docs.google.com/spreadsheets/d/1T1EkyOOBqG-Mjmlic2bDapcTE47YEVj18uYSGN1aSXk/edit?usp=sharing

== Campaign Tracker

=== Way of Thinking
The RPG campaign and party tracker provides:
- Dashboard with statistics about your campaign and party.
- Played and planned sessions overview
- Quests and pending actions; what did that old hag asked us to do again?
- Wiki sheet to track people and locations of this world
- An inventory and ledger that tracks the party's funds and cool items
- Fights and encouters aka The Kill List; who killed what when?
- Points (and Talents); track hero points and build a talent tree
- Setup. Update the dropdown lists and some advanced stuff

=== Way of Working
You fill in the sheets with the appropriate information. That's easy!
Start by updating the dashboard.
* Update the campaign information and URL's
* Complete the player names

Then update the Wiki with the character and party information
* Creata a line for each character and the party
* Do not forget to update the dashboard with the current characters

At last, during play fill in the information in the respective sheets.

=== Way of Writing

Follow the google sheet link:

Version 3.0 shared +
> https://docs.google.com/spreadsheets/d/1ovY8G8na6QeCAW9mCbqPUAoZBB73B6MwnLqcRlx2Ekg/edit?usp=share_link

Version 3.0 published +
> https://docs.google.com/spreadsheets/d/e/2PACX-1vTOvFdibmDO-ncKLH97jjsNkNdqWRHagWwYSUy8fpVvajWZECilXDBc9LOF-yTF3VbdBVwN-QWyzvr9/pubhtml

Version 2.2 shared +
> https://docs.google.com/spreadsheets/d/1hcY4uFiO1AIiaXidalKlodo1Nm-MFGM5hCZzPGHShnw/edit?usp=sharing

Instructions: +
Make a copy on your local Google Drive of the file and start taking notes.

Remark. +
Areas that are greyed out or have the text colour blue are calculated; these have formulas, update at your own risk.

That is all. Have fun!

== Requirements

A list of software that is required to contribute to this project.

[%header]
|===
| Software       | Description
| Git            | Git for version control
| Node.js        | For building the project
| Powershell     | Powershell for executing the scripts
| VS Code        | VS Code or other text editor
|===
